set encoding=utf-8
if has('gui_running')
  set guifont=Source\ Code\ Pro\ for\ Powerline:h13

  set nolist listchars=tab:▶‒,nbsp:∙,trail:∙,extends:▶,precedes:◀
  let &showbreak = '↳'
else
  set list listchars=tab:>-,nbsp:.,trail:.,extends:>,precedes:<
  let &showbreak = '^'
endif

set tabstop=2
set shiftwidth=2
set expandtab

map ; :
noremap ;; ;

call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-vinegar'
Plug 'keith/swift.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'vim-syntastic/syntastic'
Plug 'rust-lang/rust.vim'
Plug 'racer-rust/vim-racer'

call plug#end()

